### ISSUE TITLE
Live link for the project

### ISSUE THREAD

**Issue by dbc2201** [nikhil-web/Drumpad-Vanilla-JS-DEMO#1]
Do you have a live link for the project? If not, you can host your web page from the GitHub repository itself.  
Here are some links
1. [GitHub Pages](https://pages.github.com/)  
2. [Basic Steps for hosting on GitHub](https://gist.github.com/TylerFisher/6127328)  
Also, try [Patatap](https://patatap.com/).

**Comment by nikhil-web** [comment]
Thanks for the amazing advise sir. i have hosted the project on GitHub Pages
here is the link...
https://nikhil-web.github.io/Drumpad-Vanilla-JS-DEMO/
